name: Publish to GH Pages
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -t -u "github-actions-bot <support+actions@github.com>" -m "$(git show -s --format=%s)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
